services:
  db:
    image: mysql:8.0
    container_name: pets_db
    environment:
      MYSQL_DATABASE: pets_diary_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: pets_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # AQUÍ ESTÁ EL TRUCO: Sobreescribimos la configuración del properties
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pets_diary_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root